name: Sync PDF

permissions:
  write-all

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy PDF
        run: |
          # Replace with the actual paths to your PDF files
          cp meryjoy99/CV-private-/output/cv.pdf meryjoy99/public-cv/cv.pdf

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add meryjoy99/public-cv/cv.pdf
          git commit -m "Sync PDF"
          git push
