name: Sync PDF to Public Repo

permissions:
  write-all

on:
  push:
    branches:
      - main 
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug info
        run: |
          echo "Repository URL: https://github.com/meryjoy99/CV-private-.git"
          echo "Token: ${{ secrets.YOUR_MY_GITHUB_TOKEN }}"  # Replace with your secret name

      - name: Sync PDF
        run: |

          # Clone the private repo
          git clone https://github.com/meryjoy99/CV-private-.git

          # Copy the PDF to public repo
          cp output/cv.pdf public-cv/

          # Commit and push changes
          cd public-cv
          git config user.name "GitHub Actions" #should have permissions
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync PDF"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
