name: Sync PDF to Public Repo

permissions:
  write-all

on:
  push:
    branches:
      - main  # Adjust this to your default branch name

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync PDF
        run: |
          # Replace with your actual PDF file path in the private repo
          PDF_PATH="output/cv.pdf"

          # Clone the private repo
          git clone --depth 1 --branch main https://github.com/meryjoy99/CV-private-.git CV-private

          # Copy the PDF to your public repo
          cp "$PDF_PATH" public-cv/

          # Commit and push changes
          cd public-cv
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync PDF"
          git push origin main
